// Images 
import { 
  connect_four_screenshot,
  tic_tac_toe_screenshot,
  fifteen_game_screenshot,
  under_construction,
  weighing_pumpkins,
  two_passing_trains,
  rapunzels_hair,
  teenagers_ages,
  the_bent_bamboo,
  gauss_addition,
  weavers_apprentice,
  pile_of_tennis_balls,
  pirate_division,
  lockers,
  calendar,
  pentagon_coloring,
  mixing_purple_paint,
  leaning_ladder,
  monks_and_bread,
  marksmans_choice,
  goat_on_a_rope,
  brahmaguptas_egg_puzzle,
  increasing_the_average,
  buying_horses,
  finding_a_fake,
  false_alarm_virus,
  cookie_jar,
  doorway_diagonal,
  ant,
  lawn_mower,
  hens_for_the_village,
  carrot_harvest,
 } from "../../cloudinaryURLs";


export const puzzleData = [
  {
    title: "Weighing Pumpkins",
    tags: ["combinations", "logic"],
    imgUrl: weighing_pumpkins,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1hvuTFY07ifH0mVaDQigGGByZfPDz1qpiVv-jLPYdobQ/copy",
  },{
    title: "The Weaver's Apprentice",
    tags: ["fractions", "sequences"],
    imgUrl: weavers_apprentice,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1Dpy2zvJ7p0yOtDQSHx5oe_Eq9gmODGIns0P9HaQLAeM/copy",
  },{
    title: "The Marksman's Choice",
    tags: ["permutations", "tree graph"],
    imgUrl: marksmans_choice,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1GQZYTRwHXQMwpuxShL-_xw3G0eXqReEAEVxAKG7ADUk/copy",
  },{
    title: "False Positive",
    tags: ["percents", "probability"],
    imgUrl: false_alarm_virus,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1KeVREpLQs8E35LJ0VRvrvZwhaotZFWtWvnva9JG8C3Y/copy",
  },{
    title: "Goat On A Rope",
    tags: ["circles", "area"],
    imgUrl: weighing_pumpkins,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1hgHbDiItoqi7RavAcyxI_QQqZoGy1N8117IdAZR5wvE/copy",
  },{
    title: "The Ant's Path",
    tags: ["distance", "nets"],
    imgUrl: ant,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1vN9HIDnY_J5peVk4Dpublxz-xlRQm9iKzk1mg61ZA2c/copy",
  },{
    title: "The Leaning Ladders",
    tags: ["pythagorean theorem", "algebra"],
    imgUrl: leaning_ladder,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1jn3nlytLoW8lb3Qa82JjlqntJlvV7kB1a04sNJUJSk8/copy",
  },{
    title: "The Great Locker Experiment",
    tags: ["classic puzzles", "factoring", "perfect squares"],
    imgUrl: lockers,
    googleDriveCopyUrl: "https://docs.google.com/document/d/19gtGCCHNCs_CmF6KV5rTuOP4uN91fzs2YGU51L_uIs0/copy",
  },{
    title: "Pentagon Coloring",
    tags: ["symmetry", "combinations"],
    imgUrl: pentagon_coloring,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1ORHBHEMj8E4U-Q6VNQVTsmGk7ZwcYUnmooKYC9JdFn4/copy",
  },{
    title: "Pile of Tennis Balls",
    tags: ["triangle numbers", "sequences"],
    imgUrl: pile_of_tennis_balls,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1Z4pO73QqW0SFAO7feThKXpdA6i08q4x-UpiZBxVEaUg/copy",
  },{
    title: "Rapunzel's Hair",
    tags: ["pythagorean theorem", "algebra"],
    imgUrl: rapunzels_hair,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1MIkJgd-X4azvNmnph0OWiTKgUQPZruPgaNLRcMn4yFw/copy",
  },{
    title: "Doorway Diagonal",
    tags: ["pythagorean theorem", "solving quadratics"],
    imgUrl: doorway_diagonal,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1DRYOiyXSn27zdu2IUy0m1BwrdbgvWmiiF0WpnxIGJDY/copy",
  },{
    title: "Cheap Lawn Mowing",
    tags: ["linear system", "unit rates"],
    imgUrl: lawn_mower,
    googleDriveCopyUrl: "https://docs.google.com/document/d/13-SpyBxTxTRVBfsHy2SkYD2H7GrKXX9N2Hy2jClrO-c/copy",
  },{
    title: "Two Passing Trains",
    tags: ["unit rates", ""],
    imgUrl: two_passing_trains,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1-omjYqigNHESmIy-GnypDg2ZE-nYkfpa08beceN1MeA/copy",
  },{
    title: "The Paperboy Payback",
    tags: ["linear system", "fractions"],
    imgUrl: calendar,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1e2v59VBYTxX_J2YUMMUuB9K9L7j_RYpsrLAVRfUyQhs/copy",
  },{
    title: "The Bent Bamboo",
    tags: ["pythagorean theorem", ""],
    imgUrl: the_bent_bamboo,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1e4TkLGaNRSBoRRiDe9OEtflZb182kCWWPkIOai4gsWU/copy",
    source: "Crest of the Peacock",
  },{
    title: "Teenagers' Ages",
    tags: ["factoring", ""],
    imgUrl: teenagers_ages,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1R6I-ssJ53ggdXZGv8xmkL2wUDGUyzEQT4OaL4T-tYnA/copy",
    source: "",
  },{
    title: "Monks and Bread",
    tags: ["fractions", "logic"],
    imgUrl: monks_and_bread,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1ZfwWnZaTutMyBHWPF3DbIuu7HkVlhbw0H1E5-0l8iDk/copy",
    source: "Car Talk",
  },{
    title: "Mixing Purple Paint",
    tags: ["fractions", "logic"],
    imgUrl: mixing_purple_paint,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1FjItYRVTvRdtqGA0MJchYHal0m8v7FaFivaWVr7c_Xw/copy",
    source: "",
  },{
    title: "Hens for the Village",
    tags: ["linear system", "algebra"],
    imgUrl: hens_for_the_village,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1h-owfEnRP7Q2SYQhM1Bh5Q41TTjIPajLfbRPC25FT3c/copy",
    source: "Crest of the Peacock",
  },{
    title: "Gauss's Addition",
    tags: ["triangle numbers", "arithmetic series", "multiplication", "classic puzzles"],
    imgUrl: gauss_addition,
    googleDriveCopyUrl: "https://docs.google.com/document/d/10Jn5A5dfMs_COafvNh5ZdUPYe2CtbKmxX612mWx7nmg/copy",
    source: "",
  },{
    title: "Finding a Fake",
    tags: ["classic puzzles", "logic"],
    imgUrl: finding_a_fake,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1AgAWZ_0ouagOrh2V2AXw0h6Z1vD00zeYiQ-3Tv8dLs0/copy",
    source: "",
  },{
    title: "Pirate Division",
    tags: ["chinese remainder theorem", "modular arithmetic"],
    imgUrl: pirate_division,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1cVVici0uFMhZ8wsJwVPGxZh48y2lurDyP_je_uTNFqM/copy",
    source: "Number Theory Through Inquiry",
  },{
    title: "Increasing the Average",
    tags: ["unit rates", "averages"],
    imgUrl: increasing_the_average,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1ggHW27RO_J4f3-DsQaJR-nkwqy1lcnqkufXRx-iP4iI/copy",
    source: "The Moscow Puzzles",
  },{
    title: "Cookie Jar",
    tags: ["fractions", "algebra"],
    imgUrl: cookie_jar,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1Z9xC7G8jiZ09GxkiyLu11NI8UP4dgh9uy86voJVqxLw/copy",
    source: "Dr. Thatcher",
  },{
    title: "Carrot Harvest",
    tags: ["area", "factoring"],
    imgUrl: carrot_harvest,
    googleDriveCopyUrl: "https://docs.google.com/document/d/10dNsSARBYtMN5sbuh4QYuadq0FMw29plj-cZ2JTZZ68/copy",
    source: "Dr. Klein",
  },{
    title: "Buying Horses and Oxen",
    tags: ["linear systems", "modular arithmetic", "linear diophantine"],
    imgUrl: buying_horses,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1i1qjHg0dr2sEwOv3RCGV-b8vqgToD6HmS8IeV2KDcU4/copy",
    source: "Crest of the Peacock",
  },{
    title: "Brahmagupta's Egg Puzzle",
    tags: ["modular arithmetic", "chinese remainder theorem"],
    imgUrl: brahmaguptas_egg_puzzle,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1aMGXxmK4F-5S3SWJeHNgY7TRjREfdwcPDyh3O8zZ1io/copy",
    source: "Number Theory Through Inquiry",
  },
]