// Images 
import { 
  connect_four_screenshot,
  tic_tac_toe_screenshot,
  fifteen_game_screenshot,
  under_construction,
  weighing_pumpkins,
  two_passing_trains,
  rapunzels_hair,
  teenagers_ages,
  the_bent_bamboo,
  gauss_addition,
  weavers_apprentice,
  pile_of_tennis_balls,
  pirate_division,
  lockers,
  calendar,
  pentagon_coloring,
  mixing_purple_paint,
  leaning_ladder,
  monks_and_bread,
  marksmans_choice,
  goat_on_a_rope,
  brahmaguptas_egg_puzzle,
  increasing_the_average,
  buying_horses,
  finding_a_fake,
  false_alarm_virus,
  cookie_jar,
  doorway_diagonal,
  ant,
  lawn_mower
 } from "../../cloudinaryURLs";


export const puzzleData = [
  {
    title: "Weighing Pumpkins",
    tags: ["combinations", "logic"],
    imgUrl: weighing_pumpkins,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1hvuTFY07ifH0mVaDQigGGByZfPDz1qpiVv-jLPYdobQ/copy",
  },{
    title: "The Weaver's Apprentice",
    tags: ["fractions", "sequences"],
    imgUrl: weavers_apprentice,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1Dpy2zvJ7p0yOtDQSHx5oe_Eq9gmODGIns0P9HaQLAeM/copy",
  },{
    title: "The Marksman's Choice",
    tags: ["permutations", "tree graph"],
    imgUrl: marksmans_choice,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1GQZYTRwHXQMwpuxShL-_xw3G0eXqReEAEVxAKG7ADUk/copy",
  },{
    title: "False Positive",
    tags: ["percents", "probability"],
    imgUrl: false_alarm_virus,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1KeVREpLQs8E35LJ0VRvrvZwhaotZFWtWvnva9JG8C3Y/copy",
  },{
    title: "Goat On A Rope",
    tags: ["circles", "area"],
    imgUrl: weighing_pumpkins,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1hgHbDiItoqi7RavAcyxI_QQqZoGy1N8117IdAZR5wvE/copy",
  },{
    title: "The Ant's Path",
    tags: ["distance", "nets"],
    imgUrl: ant,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1vN9HIDnY_J5peVk4Dpublxz-xlRQm9iKzk1mg61ZA2c/copy",
  },{
    title: "The Leaning Ladders",
    tags: ["pythagorean theorem", "algebra"],
    imgUrl: leaning_ladder,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1jn3nlytLoW8lb3Qa82JjlqntJlvV7kB1a04sNJUJSk8/copy",
  },{
    title: "The Great Locker Experiment",
    tags: ["classic puzzles", "factoring", "perfect squares"],
    imgUrl: lockers,
    googleDriveCopyUrl: "https://docs.google.com/document/d/19gtGCCHNCs_CmF6KV5rTuOP4uN91fzs2YGU51L_uIs0/copy",
  },{
    title: "Pentagon Coloring",
    tags: ["symmetry", "combinations"],
    imgUrl: pentagon_coloring,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1ORHBHEMj8E4U-Q6VNQVTsmGk7ZwcYUnmooKYC9JdFn4/copy",
  },{
    title: "Pile of Tennis Balls",
    tags: ["triangle numbers", "sequences"],
    imgUrl: pile_of_tennis_balls,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1Z4pO73QqW0SFAO7feThKXpdA6i08q4x-UpiZBxVEaUg/copy",
  },{
    title: "Rapunzel's Hair",
    tags: ["pythagorean theorem", "algebra"],
    imgUrl: rapunzels_hair,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1MIkJgd-X4azvNmnph0OWiTKgUQPZruPgaNLRcMn4yFw/copy",
  },{
    title: "Doorway Diagonal",
    tags: ["pythagorean theorem", "solving quadratics"],
    imgUrl: doorway_diagonal,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1DRYOiyXSn27zdu2IUy0m1BwrdbgvWmiiF0WpnxIGJDY/copy",
  },{
    title: "Cheap Lawn Mowing",
    tags: ["linear system", "unit rates"],
    imgUrl: lawn_mower,
    googleDriveCopyUrl: "https://docs.google.com/document/d/13-SpyBxTxTRVBfsHy2SkYD2H7GrKXX9N2Hy2jClrO-c/copy",
  },{
    title: "Two Passing Trains",
    tags: ["unit rates", ""],
    imgUrl: two_passing_trains,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1-omjYqigNHESmIy-GnypDg2ZE-nYkfpa08beceN1MeA/copy",
  },{
    title: "The Paperboy Payback",
    tags: ["linear system", "fractions"],
    imgUrl: calendar,
    googleDriveCopyUrl: "https://docs.google.com/document/d/1e2v59VBYTxX_J2YUMMUuB9K9L7j_RYpsrLAVRfUyQhs/copy",
  },{
    title: "The Bent Bamboo",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "Crest of the Peacock",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },{
    title: "",
    tags: ["", ""],
    imgUrl: ,
    googleDriveCopyUrl: "/copy",
    source: "",
  },
]